### PR TITLE
Feature/grumphp upgrade

### PR DESCRIPTION
**Pull request by mitrpaka**
This PR fixes issue #52.

Upgrades tasks as documented in Grumphp release notes (0.18 || 0.19)
```
Extended external task class

    Make getConfigurableOptions() static
    Change service configuration + tag (config -> task)

Extended an external task from TaskInterface

    Make getConfigurableOptions() static
    Register an EmptyTaskConfig during construction
    Replace getConfiguration() method by the getConfig() method
    Add immutable withConfig() method.
    Change service configuration + tag (config -> task)

Duplicate task with different config

    Remove task copy
    Remove service configuration of task copy
    Configure task copy as an alias : https://github.com/phpro/grumphp/blob/master/doc/tasks.md#run-the-same-task-twice-with-different-configuration
```

### CODE REVIEW

**Review by tormi — APPROVED** [review]
RTBC, tested here: https://github.com/wunderio/drupal-project/pull/165 Thanks, @mitrpaka !

**Comment by tormi** [comment]
Looks like there's a packages mismatch when trying to install this with `drupal/core-recommended  8.9.10`:

```
lando composer require wunderio/code-quality:dev-feature/grumphp-upgrade --dev 
./composer.json has been updated
Running composer update wunderio/code-quality
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpro/grumphp[v1.0.0, ..., v1.2.0] require doctrine/collections ^1.6.7 -> found doctrine/collections[1.6.7, 1.6.x-dev, 1.7.x-dev] but the package is fixed to v1.4.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - wunderio/code-quality dev-feature/grumphp-upgrade requires phpro/grumphp ^1 -> satisfiable by phpro/grumphp[v1.0.0, v1.1.0, v1.2.0].
    - Root composer.json requires wunderio/code-quality dev-feature/grumphp-upgrade -> satisfiable by wunderio/code-quality[dev-feature/grumphp-upgrade].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
lando composer why doctrine/collections
commerceguys/addressing  v1.1.0  requires  doctrine/collections (~1.0)    
doctrine/common          v2.7.3  requires  doctrine/collections (1.*)     
drupal/core-recommended  8.9.10  requires  doctrine/collections (v1.4.0)  
```

**Review by tormi — CHANGES_REQUESTED** [review]
This breaks current Drupal `8.9` sites: 

```
Problem 1
    - phpro/grumphp[v1.0.0, ..., v1.2.0] require doctrine/collections ^1.6.7 -> found doctrine/collections[1.6.7, 1.6.x-dev, 1.7.x-dev] but the package is fixed to v1.4.0 (lock file version)
```

`drupal/core-recommended  8.9.10  requires  doctrine/collections (v1.4.0)`, https://github.com/drupal/core-recommended/blob/8.9.x/composer.json#L15

https://github.com/wunderio/code-quality/pull/54/#issuecomment-738231385

D 9 sites are fine because `doctrine/collections` requirement has been removed from `drupal/core-recommended`.

**Comment by tormi** [comment]
> This breaks current Drupal 8.9 sites

We've discussed this with @guncha25 last week and agreed that the solution would be to introduce new `MAJOR` version for D9 with this PR. All D 8 sites will miss the Composer 2 goodies, but let's consider this as a motivation to upgrade to D9.

**Comment by tormi** [comment]
@guncha25 also mentioned that this still needs some work from him before it can be merged.

**Review by guncha25 — APPROVED** [review]

**Comment by tormi** [comment]
👍

**Pull request merged**
